export const NCAA_ID_A: Record<string, { id: string; name: string }> = {
  "airforce": { id: "2005", name: "Air Force" },
  "akron": { id: "2006", name: "Akron" },
  "alabama": { id: "333", name: "Alabama" },
  "appalachianstate": { id: "2026", name: "Appalachian State" },
  "arizona": { id: "12", name: "Arizona" },
  "arizonastate": { id: "9", name: "Arizona State" },
  "arkansas": { id: "8", name: "Arkansas" },
  "arkansasstate": { id: "2032", name: "Arkansas State" },
  "army": { id: "349", name: "Army" },
  "auburn": { id: "2", name: "Auburn" },
  "ballstate": { id: "2050", name: "Ball State" },
  "baylor": { id: "239", name: "Baylor" },
  "bis": { id: "2449", name: "North Dakota State Bison" },
  "bison": { id: "2449", name: "North Dakota State Bison" },
  "boisestate": { id: "68", name: "Boise State" },
  "bostoncollege": { id: "103", name: "Boston College" },
  "bowlinggreen": { id: "189", name: "Bowling Green" },
  "buffalo": { id: "2084", name: "Buffalo" },
  "byu": { id: "252", name: "BYU" },
  "california": { id: "25", name: "California" },
  "centralmichigan": { id: "2117", name: "Central Michigan" },
  "charlotte": { id: "2429", name: "Charlotte" },
  "cincinnati": { id: "2132", name: "Cincinnati" },
  "clemson": { id: "228", name: "Clemson" },
  "coastalcarolina": { id: "324", name: "Coastal Carolina" },
  "colorado": { id: "38", name: "Colorado" },
  "coloradostate": { id: "36", name: "Colorado State" },
  "connecticut": { id: "41", name: "Connecticut" },
  "duke": { id: "150", name: "Duke" },
  "eastcarolina": { id: "151", name: "East Carolina" },
  "easternmichigan": { id: "2199", name: "Eastern Michigan" },
  "florida": { id: "57", name: "Florida" },
  "floridaatlantic": { id: "2226", name: "Florida Atlantic" },
  "floridainternational": { id: "2229", name: "Florida International" },
  "floridastate": { id: "52", name: "Florida State" },
  "fresnostate": { id: "278", name: "Fresno State" },
  "georgia": { id: "61", name: "Georgia" },
  "georgiasouthern": { id: "290", name: "Georgia Southern" },
  "georgiastate": { id: "2247", name: "Georgia State" },
  "georgiatech": { id: "59", name: "Georgia Tech" },
  "hawaii": { id: "62", name: "Hawaii" },
  "hor": { id: "16", name: "Sacramento State Hornets" },
  "houston": { id: "248", name: "Houston Cougars" },
  "houstoncougars": { id: "248", name: "Houston Cougars" },
  "illinois": { id: "356", name: "Illinois" },
  "indiana": { id: "84", name: "Indiana" },
  "iowa": { id: "2294", name: "Iowa" },
  "iowastate": { id: "66", name: "Iowa State" },
  "kansas": { id: "2305", name: "Kansas" },
  "kansasstate": { id: "2306", name: "Kansas State" },
  "kentstate": { id: "2309", name: "Kent State" },
  "kentucky": { id: "96", name: "Kentucky" },
  "liberty": { id: "2335", name: "Liberty" },
  "louisiana": { id: "309", name: "Louisiana" },
  "louisianamonroe": { id: "2433", name: "Louisiana Monroe" },
  "louisianatech": { id: "2348", name: "Louisiana Tech" },
  "louisville": { id: "97", name: "Louisville" },
  "lsu": { id: "99", name: "LSU" },
  "marshall": { id: "276", name: "Marshall" },
  "maryland": { id: "120", name: "Maryland" },
  "memphis": { id: "235", name: "Memphis" },
  "miami": { id: "2390", name: "Miami Hurricanes" },
  "miamihurricanes": { id: "2390", name: "Miami Hurricanes" },
  "miamioh": { id: "193", name: "Miami (OH)" },
  "michigan": { id: "130", name: "Michigan" },
  "michiganstate": { id: "127", name: "Michigan State" },
  "middletennessee": { id: "2393", name: "Middle Tennessee" },
  "minnesota": { id: "135", name: "Minnesota" },
  "mississippistate": { id: "344", name: "Mississippi State" },
  "missouri": { id: "142", name: "Missouri" },
  "navy": { id: "2426", name: "Navy" },
};
