export const NCAA_ID_B: Record<string, { id: string; name: string }> = {
  "ncstate": { id: "152", name: "NC State" },
  "ndsu": { id: "2449", name: "North Dakota State Bison" },
  "nebraska": { id: "158", name: "Nebraska" },
  "nevada": { id: "2440", name: "Nevada" },
  "newmexico": { id: "167", name: "New Mexico" },
  "newmexicostate": { id: "166", name: "New Mexico State" },
  "northcarolina": { id: "153", name: "North Carolina" },
  "northdakotastate": { id: "2449", name: "North Dakota State Bison" },
  "northdakotastatebison": { id: "2449", name: "North Dakota State Bison" },
  "northernillinois": { id: "2459", name: "Northern Illinois" },
  "northtexas": { id: "249", name: "North Texas" },
  "northwestern": { id: "77", name: "Northwestern" },
  "notredame": { id: "87", name: "Notre Dame" },
  "ohio": { id: "195", name: "Ohio" },
  "ohiostate": { id: "194", name: "Ohio State" },
  "oklahoma": { id: "201", name: "Oklahoma" },
  "oklahomastate": { id: "197", name: "Oklahoma State" },
  "olddominion": { id: "295", name: "Old Dominion" },
  "olemiss": { id: "145", name: "Ole Miss" },
  "oregon": { id: "2483", name: "Oregon" },
  "oregonstate": { id: "204", name: "Oregon State" },
  "pennstate": { id: "213", name: "Penn State" },
  "pittsburgh": { id: "221", name: "Pittsburgh" },
  "purdue": { id: "2509", name: "Purdue" },
  "rice": { id: "242", name: "Rice" },
  "rutgers": { id: "164", name: "Rutgers" },
  "sacramentostate": { id: "16", name: "Sacramento State Hornets" },
  "sacramentostatehornets": { id: "16", name: "Sacramento State Hornets" },
  "sacstate": { id: "16", name: "Sacramento State Hornets" },
  "sandiegostate": { id: "21", name: "San Diego State" },
  "sanjosestate": { id: "23", name: "San Jose State" },
  "smu": { id: "2567", name: "SMU" },
  "southalabama": { id: "6", name: "South Alabama" },
  "southcarolina": { id: "2579", name: "South Carolina" },
  "southernmississippi": { id: "2572", name: "Southern Mississippi" },
  "southflorida": { id: "58", name: "South Florida" },
  "stanford": { id: "24", name: "Stanford" },
  "syracuse": { id: "183", name: "Syracuse" },
  "tcu": { id: "2628", name: "TCU" },
  "temple": { id: "218", name: "Temple" },
  "tennessee": { id: "2633", name: "Tennessee" },
  "texas": { id: "251", name: "Texas" },
  "texasam": { id: "245", name: "Texas A&M" },
  "texasstate": { id: "326", name: "Texas State" },
  "texastech": { id: "2641", name: "Texas Tech Red Raiders" },
  "texastechredraiders": { id: "2641", name: "Texas Tech Red Raiders" },
  "toledo": { id: "2649", name: "Toledo" },
  "troy": { id: "2653", name: "Troy" },
  "tulane": { id: "2655", name: "Tulane" },
  "tulsa": { id: "202", name: "Tulsa" },
  "uab": { id: "5", name: "UAB" },
  "ucf": { id: "2116", name: "UCF" },
  "ucla": { id: "26", name: "UCLA" },
  "umass": { id: "113", name: "UMass" },
  "unlv": { id: "2439", name: "UNLV" },
  "usc": { id: "30", name: "USC" },
  "utah": { id: "254", name: "Utah" },
  "utahstate": { id: "328", name: "Utah State" },
  "utep": { id: "2638", name: "UTEP" },
  "utsanantonio": { id: "2636", name: "UT San Antonio" },
  "vanderbilt": { id: "238", name: "Vanderbilt" },
  "virginia": { id: "258", name: "Virginia" },
  "virginiatech": { id: "259", name: "Virginia Tech" },
  "wakeforest": { id: "154", name: "Wake Forest Demon Deacons" },
  "wakeforestdemondeacons": { id: "154", name: "Wake Forest Demon Deacons" },
  "washington": { id: "264", name: "Washington" },
  "washingtonstate": { id: "265", name: "Washington State" },
  "westernkentucky": { id: "98", name: "Western Kentucky" },
  "westernmichigan": { id: "2711", name: "Western Michigan" },
  "westvirginia": { id: "277", name: "West Virginia" },
  "wisconsin": { id: "275", name: "Wisconsin" },
  "wyoming": { id: "2751", name: "Wyoming" },
};
