import { createFileRoute } from "@tanstack/react-router";
import { getPredictionLogs } from "@/lib/market/server";

export const Route = createFileRoute("/brain")({
  loader: async () => {
    return getPredictionLogs();
  },
  component: BrainDashboard,
});

function BrainDashboard() {
  const logs = Route.useLoaderData() as any[];

  const wins = logs.filter((l) => l.status === "WIN").length;
  const losses = logs.filter((l) => l.status === "LOSS").length;
  const pushes = logs.filter((l) => l.status === "PUSH").length;
  const pending = logs.filter((l) => l.status === "PENDING").length;

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 p-6 md:p-12 font-mono">
      <div className="max-w-5xl mx-auto space-y-8">
        
        {/* Header / Metrics */}
        <header className="space-y-4">
          <h1 className="text-3xl font-bold tracking-tight text-white flex items-center gap-3">
            <span className="text-emerald-500">■</span> Intelligence Terminal
          </h1>
          <p className="text-zinc-400 max-w-2xl">
            Autoregressive Learning Engine telemetry. Automated paper-trading sweeps and post-game autopsy reports generated by the Gemini model.
          </p>

          <div className="flex flex-wrap gap-4 pt-4">
            <div className="bg-zinc-900 border border-zinc-800 rounded-lg px-4 py-3 min-w-[120px]">
              <div className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mb-1">Win/Loss</div>
              <div className="text-2xl font-bold text-zinc-100">
                <span className="text-emerald-500">{wins}</span>
                <span className="text-zinc-600 mx-1">-</span>
                <span className="text-red-500">{losses}</span>
                {pushes > 0 && (
                  <>
                    <span className="text-zinc-600 mx-1">-</span>
                    <span className="text-amber-500">{pushes}</span>
                  </>
                )}
              </div>
            </div>
            
            <div className="bg-zinc-900 border border-zinc-800 rounded-lg px-4 py-3 min-w-[120px]">
              <div className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mb-1">Pending</div>
              <div className="text-2xl font-bold text-zinc-100">{pending}</div>
            </div>

            <div className="bg-zinc-900 border border-zinc-800 rounded-lg px-4 py-3 min-w-[120px]">
              <div className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mb-1">Total Logs</div>
              <div className="text-2xl font-bold text-zinc-100">{logs.length}</div>
            </div>
          </div>
        </header>

        {/* The Autopsy Feed */}
        <section className="space-y-4">
          <h2 className="text-lg font-semibold text-zinc-300 border-b border-zinc-800 pb-2">Prediction Ledger</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {logs.map((log) => {
              const isWin = log.status === "WIN";
              const isLoss = log.status === "LOSS";
              const isPush = log.status === "PUSH";
              
              const autopsyText = log.ai_autopsy || "";
              const isModelError = autopsyText.includes("MODEL ERROR");
              const isHighVariance = autopsyText.includes("HIGH VARIANCE");

              let borderColor = "border-zinc-800";
              if (isWin) borderColor = "border-emerald-500/50";
              else if (isLoss && isModelError) borderColor = "border-red-500/60";
              else if (isLoss && isHighVariance) borderColor = "border-amber-500/60";
              else if (isPush) borderColor = "border-amber-500/30";

              let badgeColor = "bg-zinc-800 text-zinc-300";
              if (isWin) badgeColor = "bg-emerald-500/20 text-emerald-400";
              else if (isLoss) badgeColor = "bg-red-500/20 text-red-400";
              else if (isPush) badgeColor = "bg-amber-500/20 text-amber-400";
              else if (log.status === "PENDING") badgeColor = "bg-blue-500/20 text-blue-400";

              return (
                <div key={log.id} className={`bg-zinc-900 border rounded-xl p-5 space-y-4 flex flex-col ${borderColor} transition-colors`}>
                  <div className="flex justify-between items-start gap-4">
                    <div>
                      <h3 className="font-bold text-zinc-100">{log.selection}</h3>
                      <div className="text-sm text-zinc-400 mt-1 capitalize">
                        {log.market_type} {log.line != null ? `(${log.line > 0 ? '+' : ''}${log.line})` : ''}
                      </div>
                    </div>
                    <div className={`text-xs font-bold px-2 py-1 rounded uppercase tracking-wider ${badgeColor}`}>
                      {log.status}
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-2 text-sm bg-zinc-950 p-3 rounded-lg border border-zinc-800/50">
                    <div>
                      <span className="text-zinc-500 block text-xs mb-0.5">Price</span>
                      <span className="text-zinc-200">{log.price > 0 ? '+' : ''}{log.price}</span>
                    </div>
                    <div>
                      <span className="text-zinc-500 block text-xs mb-0.5">Calculated Edge</span>
                      <span className="text-emerald-400">{(log.edge * 100).toFixed(2)}%</span>
                    </div>
                  </div>

                  {isLoss && autopsyText && (
                    <div className="flex-1 mt-2">
                      <div className="text-xs text-zinc-500 font-bold tracking-wider mb-2 flex items-center gap-2">
                        <span className="text-indigo-400">✧</span> AI AUTOPSY
                      </div>
                      <p className="text-sm text-zinc-300 leading-relaxed italic border-l-2 border-indigo-500/30 pl-3">
                        "{autopsyText}"
                      </p>
                    </div>
                  )}
                </div>
              );
            })}
            
            {logs.length === 0 && (
              <div className="col-span-full py-12 text-center border border-dashed border-zinc-800 rounded-xl text-zinc-500">
                No prediction logs found in the ledger.
              </div>
            )}
          </div>
        </section>

      </div>
    </div>
  );
}