/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminAnalysisRouteImport } from './routes/admin/analysis'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAutopsyRouteImport } from './routes/admin/autopsy'
import { Route as AdminBrainRouteImport } from './routes/admin/brain'
import { Route as AdminBrainIntelRouteImport } from './routes/admin/brain-intel'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEngineRouteImport } from './routes/admin/engine'
import { Route as AdminOverridesRouteImport } from './routes/admin/overrides'
import { Route as AdminPredictionsRouteImport } from './routes/admin/predictions'
import { Route as AdminSuggestionsRouteImport } from './routes/admin/suggestions'
import { Route as AdminTerminalRouteImport } from './routes/admin/terminal'
import { Route as GameEventIdRouteImport } from './routes/game.$eventId'
import { Route as ApiAdminStrategyRouteImport } from './routes/api/admin/strategy'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronAutopsyRouteImport } from './routes/api/cron/autopsy'
import { Route as ApiCronBrainLearnRouteImport } from './routes/api/cron/brain-learn'
import { Route as ApiCronGradeRouteImport } from './routes/api/cron/grade'
import { Route as ApiCronGradePropsRouteImport } from './routes/api/cron/grade-props'
import { Route as ApiCronMorningPullRouteImport } from './routes/api/cron/morning-pull'
import { Route as ApiCronSweepRouteImport } from './routes/api/cron/sweep'
import { Route as ApiCronSweepLedgerRouteImport } from './routes/api/cron/sweep-ledger'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalysisRoute = AdminAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutopsyRoute = AdminAutopsyRouteImport.update({
  id: '/autopsy',
  path: '/autopsy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrainRoute = AdminBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrainIntelRoute = AdminBrainIntelRouteImport.update({
  id: '/brain-intel',
  path: '/brain-intel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngineRoute = AdminEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverridesRoute = AdminOverridesRouteImport.update({
  id: '/overrides',
  path: '/overrides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuggestionsRoute = AdminSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTerminalRoute = AdminTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AdminRoute,
} as any)
const GameEventIdRoute = GameEventIdRouteImport.update({
  id: '/game/$eventId',
  path: '/game/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStrategyRoute = ApiAdminStrategyRouteImport.update({
  id: '/api/admin/strategy',
  path: '/api/admin/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutopsyRoute = ApiCronAutopsyRouteImport.update({
  id: '/api/cron/autopsy',
  path: '/api/cron/autopsy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBrainLearnRoute = ApiCronBrainLearnRouteImport.update({
  id: '/api/cron/brain-learn',
  path: '/api/cron/brain-learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGradeRoute = ApiCronGradeRouteImport.update({
  id: '/api/cron/grade',
  path: '/api/cron/grade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGradePropsRoute = ApiCronGradePropsRouteImport.update({
  id: '/api/cron/grade-props',
  path: '/api/cron/grade-props',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMorningPullRoute = ApiCronMorningPullRouteImport.update({
  id: '/api/cron/morning-pull',
  path: '/api/cron/morning-pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSweepRoute = ApiCronSweepRouteImport.update({
  id: '/api/cron/sweep',
  path: '/api/cron/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSweepLedgerRoute = ApiCronSweepLedgerRouteImport.update({
  id: '/api/cron/sweep-ledger',
  path: '/api/cron/sweep-ledger',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arbitrage': typeof ArbitrageRoute
  '/desk': typeof DeskRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/picks': typeof PicksRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/ticket': typeof TicketRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/autopsy': typeof AdminAutopsyRoute
  '/admin/brain': typeof AdminBrainRoute
  '/admin/brain-intel': typeof AdminBrainIntelRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/engine': typeof AdminEngineRoute
  '/admin/overrides': typeof AdminOverridesRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/terminal': typeof AdminTerminalRoute
  '/game/$eventId': typeof GameEventIdRoute
  '/api/admin/strategy': typeof ApiAdminStrategyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/autopsy': typeof ApiCronAutopsyRoute
  '/api/cron/brain-learn': typeof ApiCronBrainLearnRoute
  '/api/cron/grade': typeof ApiCronGradeRoute
  '/api/cron/grade-props': typeof ApiCronGradePropsRoute
  '/api/cron/morning-pull': typeof ApiCronMorningPullRoute
  '/api/cron/sweep': typeof ApiCronSweepRoute
  '/api/cron/sweep-ledger': typeof ApiCronSweepLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arbitrage': typeof ArbitrageRoute
  '/desk': typeof DeskRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/picks': typeof PicksRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/ticket': typeof TicketRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/autopsy': typeof AdminAutopsyRoute
  '/admin/brain': typeof AdminBrainRoute
  '/admin/brain-intel': typeof AdminBrainIntelRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/engine': typeof AdminEngineRoute
  '/admin/overrides': typeof AdminOverridesRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/terminal': typeof AdminTerminalRoute
  '/game/$eventId': typeof GameEventIdRoute
  '/api/admin/strategy': typeof ApiAdminStrategyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/autopsy': typeof ApiCronAutopsyRoute
  '/api/cron/brain-learn': typeof ApiCronBrainLearnRoute
  '/api/cron/grade': typeof ApiCronGradeRoute
  '/api/cron/grade-props': typeof ApiCronGradePropsRoute
  '/api/cron/morning-pull': typeof ApiCronMorningPullRoute
  '/api/cron/sweep': typeof ApiCronSweepRoute
  '/api/cron/sweep-ledger': typeof ApiCronSweepLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arbitrage': typeof ArbitrageRoute
  '/desk': typeof DeskRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/picks': typeof PicksRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/ticket': typeof TicketRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/autopsy': typeof AdminAutopsyRoute
  '/admin/brain': typeof AdminBrainRoute
  '/admin/brain-intel': typeof AdminBrainIntelRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/engine': typeof AdminEngineRoute
  '/admin/overrides': typeof AdminOverridesRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/terminal': typeof AdminTerminalRoute
  '/game/$eventId': typeof GameEventIdRoute
  '/api/admin/strategy': typeof ApiAdminStrategyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/autopsy': typeof ApiCronAutopsyRoute
  '/api/cron/brain-learn': typeof ApiCronBrainLearnRoute
  '/api/cron/grade': typeof ApiCronGradeRoute
  '/api/cron/grade-props': typeof ApiCronGradePropsRoute
  '/api/cron/morning-pull': typeof ApiCronMorningPullRoute
  '/api/cron/sweep': typeof ApiCronSweepRoute
  '/api/cron/sweep-ledger': typeof ApiCronSweepLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arbitrage'
    | '/desk'
    | '/games'
    | '/login'
    | '/picks'
    | '/profile'
    | '/results'
    | '/ticket'
    | '/admin/activity'
    | '/admin/analysis'
    | '/admin/approvals'
    | '/admin/autopsy'
    | '/admin/brain'
    | '/admin/brain-intel'
    | '/admin/dashboard'
    | '/admin/engine'
    | '/admin/overrides'
    | '/admin/predictions'
    | '/admin/suggestions'
    | '/admin/terminal'
    | '/game/$eventId'
    | '/api/admin/strategy'
    | '/api/auth/$'
    | '/api/cron/autopsy'
    | '/api/cron/brain-learn'
    | '/api/cron/grade'
    | '/api/cron/grade-props'
    | '/api/cron/morning-pull'
    | '/api/cron/sweep'
    | '/api/cron/sweep-ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arbitrage'
    | '/desk'
    | '/games'
    | '/login'
    | '/picks'
    | '/profile'
    | '/results'
    | '/ticket'
    | '/admin/activity'
    | '/admin/analysis'
    | '/admin/approvals'
    | '/admin/autopsy'
    | '/admin/brain'
    | '/admin/brain-intel'
    | '/admin/dashboard'
    | '/admin/engine'
    | '/admin/overrides'
    | '/admin/predictions'
    | '/admin/suggestions'
    | '/admin/terminal'
    | '/game/$eventId'
    | '/api/admin/strategy'
    | '/api/auth/$'
    | '/api/cron/autopsy'
    | '/api/cron/brain-learn'
    | '/api/cron/grade'
    | '/api/cron/grade-props'
    | '/api/cron/morning-pull'
    | '/api/cron/sweep'
    | '/api/cron/sweep-ledger'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arbitrage'
    | '/desk'
    | '/games'
    | '/login'
    | '/picks'
    | '/profile'
    | '/results'
    | '/ticket'
    | '/admin/activity'
    | '/admin/analysis'
    | '/admin/approvals'
    | '/admin/autopsy'
    | '/admin/brain'
    | '/admin/brain-intel'
    | '/admin/dashboard'
    | '/admin/engine'
    | '/admin/overrides'
    | '/admin/predictions'
    | '/admin/suggestions'
    | '/admin/terminal'
    | '/game/$eventId'
    | '/api/admin/strategy'
    | '/api/auth/$'
    | '/api/cron/autopsy'
    | '/api/cron/brain-learn'
    | '/api/cron/grade'
    | '/api/cron/grade-props'
    | '/api/cron/morning-pull'
    | '/api/cron/sweep'
    | '/api/cron/sweep-ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArbitrageRoute: typeof ArbitrageRoute
  DeskRoute: typeof DeskRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  PicksRoute: typeof PicksRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  TicketRoute: typeof TicketRoute
  GameEventIdRoute: typeof GameEventIdRoute
  ApiAdminStrategyRoute: typeof ApiAdminStrategyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronAutopsyRoute: typeof ApiCronAutopsyRoute
  ApiCronBrainLearnRoute: typeof ApiCronBrainLearnRoute
  ApiCronGradeRoute: typeof ApiCronGradeRoute
  ApiCronGradePropsRoute: typeof ApiCronGradePropsRoute
  ApiCronMorningPullRoute: typeof ApiCronMorningPullRoute
  ApiCronSweepRoute: typeof ApiCronSweepRoute
  ApiCronSweepLedgerRoute: typeof ApiCronSweepLedgerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analysis': {
      id: '/admin/analysis'
      path: '/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof AdminAnalysisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/autopsy': {
      id: '/admin/autopsy'
      path: '/autopsy'
      fullPath: '/admin/autopsy'
      preLoaderRoute: typeof AdminAutopsyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brain': {
      id: '/admin/brain'
      path: '/brain'
      fullPath: '/admin/brain'
      preLoaderRoute: typeof AdminBrainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brain-intel': {
      id: '/admin/brain-intel'
      path: '/brain-intel'
      fullPath: '/admin/brain-intel'
      preLoaderRoute: typeof AdminBrainIntelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engine': {
      id: '/admin/engine'
      path: '/engine'
      fullPath: '/admin/engine'
      preLoaderRoute: typeof AdminEngineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overrides': {
      id: '/admin/overrides'
      path: '/overrides'
      fullPath: '/admin/overrides'
      preLoaderRoute: typeof AdminOverridesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suggestions': {
      id: '/admin/suggestions'
      path: '/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AdminSuggestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/terminal': {
      id: '/admin/terminal'
      path: '/terminal'
      fullPath: '/admin/terminal'
      preLoaderRoute: typeof AdminTerminalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/game/$eventId': {
      id: '/game/$eventId'
      path: '/game/$eventId'
      fullPath: '/game/$eventId'
      preLoaderRoute: typeof GameEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/strategy': {
      id: '/api/admin/strategy'
      path: '/api/admin/strategy'
      fullPath: '/api/admin/strategy'
      preLoaderRoute: typeof ApiAdminStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/autopsy': {
      id: '/api/cron/autopsy'
      path: '/api/cron/autopsy'
      fullPath: '/api/cron/autopsy'
      preLoaderRoute: typeof ApiCronAutopsyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/brain-learn': {
      id: '/api/cron/brain-learn'
      path: '/api/cron/brain-learn'
      fullPath: '/api/cron/brain-learn'
      preLoaderRoute: typeof ApiCronBrainLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/grade': {
      id: '/api/cron/grade'
      path: '/api/cron/grade'
      fullPath: '/api/cron/grade'
      preLoaderRoute: typeof ApiCronGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/grade-props': {
      id: '/api/cron/grade-props'
      path: '/api/cron/grade-props'
      fullPath: '/api/cron/grade-props'
      preLoaderRoute: typeof ApiCronGradePropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/morning-pull': {
      id: '/api/cron/morning-pull'
      path: '/api/cron/morning-pull'
      fullPath: '/api/cron/morning-pull'
      preLoaderRoute: typeof ApiCronMorningPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sweep': {
      id: '/api/cron/sweep'
      path: '/api/cron/sweep'
      fullPath: '/api/cron/sweep'
      preLoaderRoute: typeof ApiCronSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sweep-ledger': {
      id: '/api/cron/sweep-ledger'
      path: '/api/cron/sweep-ledger'
      fullPath: '/api/cron/sweep-ledger'
      preLoaderRoute: typeof ApiCronSweepLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalysisRoute: typeof AdminAnalysisRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAutopsyRoute: typeof AdminAutopsyRoute
  AdminBrainRoute: typeof AdminBrainRoute
  AdminBrainIntelRoute: typeof AdminBrainIntelRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEngineRoute: typeof AdminEngineRoute
  AdminOverridesRoute: typeof AdminOverridesRoute
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminSuggestionsRoute: typeof AdminSuggestionsRoute
  AdminTerminalRoute: typeof AdminTerminalRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalysisRoute: AdminAnalysisRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAutopsyRoute: AdminAutopsyRoute,
  AdminBrainRoute: AdminBrainRoute,
  AdminBrainIntelRoute: AdminBrainIntelRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEngineRoute: AdminEngineRoute,
  AdminOverridesRoute: AdminOverridesRoute,
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminSuggestionsRoute: AdminSuggestionsRoute,
  AdminTerminalRoute: AdminTerminalRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArbitrageRoute: ArbitrageRoute,
  DeskRoute: DeskRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  PicksRoute: PicksRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  TicketRoute: TicketRoute,
  GameEventIdRoute: GameEventIdRoute,
  ApiAdminStrategyRoute: ApiAdminStrategyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronAutopsyRoute: ApiCronAutopsyRoute,
  ApiCronBrainLearnRoute: ApiCronBrainLearnRoute,
  ApiCronGradeRoute: ApiCronGradeRoute,
  ApiCronGradePropsRoute: ApiCronGradePropsRoute,
  ApiCronMorningPullRoute: ApiCronMorningPullRoute,
  ApiCronSweepRoute: ApiCronSweepRoute,
  ApiCronSweepLedgerRoute: ApiCronSweepLedgerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
