/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminTerminalRouteImport } from './routes/admin/terminal'
import { Route as AdminArchitectRouteImport } from './routes/admin/architect'
import { Route as AdminBrainRouteImport } from './routes/admin/brain'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GamedayRouteImport } from './routes/gameday'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as ParlayRouteImport } from './routes/parlay'
import { Route as PathRouteImport } from './routes/path'
import { Route as SlateRouteImport } from './routes/slate'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as TodayRouteImport } from './routes/today'
import { Route as GameEventIdRouteImport } from './routes/game.$eventId'
import { Route as OptionKindRouteImport } from './routes/option.$kind'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTerminalRoute = AdminTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchitectRoute = AdminArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrainRoute = AdminBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AdminRoute,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GamedayRoute = GamedayRouteImport.update({
  id: '/gameday',
  path: '/gameday',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ParlayRoute = ParlayRouteImport.update({
  id: '/parlay',
  path: '/parlay',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const SlateRoute = SlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const GameEventIdRoute = GameEventIdRouteImport.update({
  id: '/game/$eventId',
  path: '/game/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionKindRoute = OptionKindRouteImport.update({
  id: '/option/$kind',
  path: '/option/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/admin/architect': typeof AdminArchitectRoute
    '/admin/terminal': typeof AdminTerminalRoute
    '/admin/brain': typeof AdminBrainRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/board': typeof BoardRoute
  '/desk': typeof DeskRoute
  '/gameday': typeof GamedayRoute
  '/guide': typeof GuideRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/options': typeof OptionsRoute
  '/parlay': typeof ParlayRoute
  '/path': typeof PathRoute
  '/slate': typeof SlateRoute
  '/ticket': typeof TicketRoute
  '/today': typeof TodayRoute
  '/game/$eventId': typeof GameEventIdRoute
  '/option/$kind': typeof OptionKindRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
    '/admin/architect': typeof AdminArchitectRoute
    '/admin/terminal': typeof AdminTerminalRoute
    '/admin/brain': typeof AdminBrainRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/board': typeof BoardRoute
  '/desk': typeof DeskRoute
  '/gameday': typeof GamedayRoute
  '/guide': typeof GuideRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/options': typeof OptionsRoute
  '/parlay': typeof ParlayRoute
  '/path': typeof PathRoute
  '/slate': typeof SlateRoute
  '/ticket': typeof TicketRoute
  '/today': typeof TodayRoute
  '/game/$eventId': typeof GameEventIdRoute
  '/option/$kind': typeof OptionKindRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
    '/admin/architect': typeof AdminArchitectRoute
    '/admin/terminal': typeof AdminTerminalRoute
    '/admin/brain': typeof AdminBrainRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/board': typeof BoardRoute
  '/desk': typeof DeskRoute
  '/gameday': typeof GamedayRoute
  '/guide': typeof GuideRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/options': typeof OptionsRoute
  '/parlay': typeof ParlayRoute
  '/path': typeof PathRoute
  '/slate': typeof SlateRoute
  '/ticket': typeof TicketRoute
  '/today': typeof TodayRoute
  '/game/$eventId': typeof GameEventIdRoute
  '/option/$kind': typeof OptionKindRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
      | '/'
      | '/admin/architect'
      | '/admin/brain'
      | '/admin/terminal'
    | '/admin'
    | '/alerts'
    | '/board'
    | '/desk'
    | '/gameday'
    | '/guide'
    | '/learn'
    | '/live'
    | '/login'
    | '/more'
    | '/options'
    | '/parlay'
    | '/path'
    | '/slate'
    | '/ticket'
    | '/today'
    | '/game/$eventId'
    | '/option/$kind'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
    to:
      | '/'
      | '/admin/architect'
      | '/admin/brain'
      | '/admin/terminal'
    | '/admin'
    | '/alerts'
    | '/board'
    | '/desk'
    | '/gameday'
    | '/guide'
    | '/learn'
    | '/live'
    | '/login'
    | '/more'
    | '/options'
    | '/parlay'
    | '/path'
    | '/slate'
    | '/ticket'
    | '/today'
    | '/game/$eventId'
    | '/option/$kind'
    | '/api/auth/$'
    id:
      | '__root__'
      | '/'
      | '/admin/architect'
      | '/admin/brain'
      | '/admin/terminal'
    | '/admin'
    | '/alerts'
    | '/board'
    | '/desk'
    | '/gameday'
    | '/guide'
    | '/learn'
    | '/live'
    | '/login'
    | '/more'
    | '/options'
    | '/parlay'
    | '/path'
    | '/slate'
    | '/ticket'
    | '/today'
    | '/game/$eventId'
    | '/option/$kind'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  BoardRoute: typeof BoardRoute
  DeskRoute: typeof DeskRoute
  GamedayRoute: typeof GamedayRoute
  GuideRoute: typeof GuideRoute
  LearnRoute: typeof LearnRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  OptionsRoute: typeof OptionsRoute
  ParlayRoute: typeof ParlayRoute
  PathRoute: typeof PathRoute
  SlateRoute: typeof SlateRoute
  TicketRoute: typeof TicketRoute
  TodayRoute: typeof TodayRoute
  GameEventIdRoute: typeof GameEventIdRoute
  OptionKindRoute: typeof OptionKindRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
      '/admin': {
        id: '/admin'
        path: '/admin'
        fullPath: '/admin'
        preLoaderRoute: typeof AdminRouteImport
        parentRoute: typeof rootRouteImport
      }
      '/admin/architect': {
        id: '/admin/architect'
        path: '/architect'
        fullPath: '/admin/architect'
        preLoaderRoute: typeof AdminArchitectRouteImport
        parentRoute: typeof AdminRouteImport
      }
      '/admin/terminal': {
        id: '/admin/terminal'
        path: '/terminal'
        fullPath: '/admin/terminal'
        preLoaderRoute: typeof AdminTerminalRouteImport
                parentRoute: typeof AdminRouteImport
      }
      '/admin/brain': {
        id: '/admin/brain'
        path: '/brain'
        fullPath: '/admin/brain'
        preLoaderRoute: typeof AdminBrainRouteImport
        parentRoute: typeof AdminRouteImport
      }
      '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameday': {
      id: '/gameday'
      path: '/gameday'
      fullPath: '/gameday'
      preLoaderRoute: typeof GamedayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parlay': {
      id: '/parlay'
      path: '/parlay'
      fullPath: '/parlay'
      preLoaderRoute: typeof ParlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slate': {
      id: '/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof SlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$eventId': {
      id: '/game/$eventId'
      path: '/game/$eventId'
      fullPath: '/game/$eventId'
      preLoaderRoute: typeof GameEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option/$kind': {
      id: '/option/$kind'
      path: '/option/$kind'
      fullPath: '/option/$kind'
      preLoaderRoute: typeof OptionKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const AdminRouteWithChildren = AdminRoute._addFileChildren({
  AdminArchitectRoute: AdminArchitectRoute,
  AdminBrainRoute: AdminBrainRoute,
  AdminTerminalRoute: AdminTerminalRoute,
})

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  BoardRoute: BoardRoute,
  DeskRoute: DeskRoute,
  GamedayRoute: GamedayRoute,
  GuideRoute: GuideRoute,
  LearnRoute: LearnRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  OptionsRoute: OptionsRoute,
  ParlayRoute: ParlayRoute,
  PathRoute: PathRoute,
  SlateRoute: SlateRoute,
  TicketRoute: TicketRoute,
  TodayRoute: TodayRoute,
  GameEventIdRoute: GameEventIdRoute,
  OptionKindRoute: OptionKindRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
